name: Run Scraper

on:
  schedule:
    # - cron: '*/5 * * * *'  # Runs every 5 minutes.
    - cron: '0 12 * * *'  # Runs every day at noon UTC. Adjust to your needs.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install dependencies
      run: |
        pip install --no-cache-dir -v -r requirements.txt

    - name: Run script
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      run: |
        python main.py
